title: Dan Chan
description: >
  software engineer @ galileo.io
permalink: ':title/'
baseurl: ""
url: "https://brokenthumbs.github.io"
site-twitter:

author: Dan Chan
author-img: dan-chan.jpg
about-author: >
  software engineer @ galileo.io<br />
social-twitter: brokenthumbs
social-instagram: brokenthumbs
social-github: brokenthumbs
social-linkedin: dbtchan
social-email: dbtchan@gmail.com

# Disqus
discus-identifier:

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
